# Generated by Django 6.0.1 on 2026-01-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating', '-reviews'],
                'indexes': [models.Index(fields=['cuisine'], name='restaurants_cuisine_6e1775_idx'), models.Index(fields=['-rating'], name='restaurants_rating_be9896_idx')],
            },
        ),
    ]
